CREATE TABLE "project_momentum" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"calculated_at" timestamp with time zone NOT NULL,
	"current_snapshot_id" uuid NOT NULL,
	"weekly_snapshot_id" uuid,
	"monthly_snapshot_id" uuid,
	"stars" integer NOT NULL,
	"absolute_7d" integer,
	"absolute_30d" integer,
	"relative_7d" real,
	"relative_30d" real,
	"activity_factor" real NOT NULL,
	"score" real,
	"confidence" text NOT NULL,
	"window_start" timestamp with time zone,
	"window_end" timestamp with time zone NOT NULL,
	"anomaly" boolean DEFAULT false NOT NULL,
	"anomaly_reasons" jsonb NOT NULL,
	"algorithm_version" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "search_aliases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project_id" uuid NOT NULL,
	"alias" text NOT NULL,
	"normalized_alias" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "search_zero_results" (
	"query_hash" text PRIMARY KEY NOT NULL,
	"normalized_query" text NOT NULL,
	"count" integer DEFAULT 1 NOT NULL,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "facets" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "github_snapshots" ADD COLUMN "response_etag" text;--> statement-breakpoint
ALTER TABLE "github_snapshots" ADD COLUMN "request_outcome" text DEFAULT '200' NOT NULL;--> statement-breakpoint
ALTER TABLE "github_snapshots" ADD COLUMN "collector_version" text DEFAULT 'v1' NOT NULL;--> statement-breakpoint
ALTER TABLE "repositories" ADD COLUMN "html_url" text;--> statement-breakpoint
ALTER TABLE "repositories" ADD COLUMN "default_branch" text;--> statement-breakpoint
ALTER TABLE "repositories" ADD COLUMN "archived" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "repositories" ADD COLUMN "private" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "repositories" ADD COLUMN "manually_excluded" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "repositories" ADD COLUMN "exclusion_reason" text;--> statement-breakpoint
ALTER TABLE "repositories" ADD COLUMN "sync_status" text DEFAULT 'pending' NOT NULL;--> statement-breakpoint
ALTER TABLE "repositories" ADD COLUMN "last_attempt_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "repositories" ADD COLUMN "consecutive_failures" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "project_momentum" ADD CONSTRAINT "project_momentum_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_momentum" ADD CONSTRAINT "project_momentum_current_snapshot_id_github_snapshots_id_fk" FOREIGN KEY ("current_snapshot_id") REFERENCES "public"."github_snapshots"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_momentum" ADD CONSTRAINT "project_momentum_weekly_snapshot_id_github_snapshots_id_fk" FOREIGN KEY ("weekly_snapshot_id") REFERENCES "public"."github_snapshots"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_momentum" ADD CONSTRAINT "project_momentum_monthly_snapshot_id_github_snapshots_id_fk" FOREIGN KEY ("monthly_snapshot_id") REFERENCES "public"."github_snapshots"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_aliases" ADD CONSTRAINT "search_aliases_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "project_momentum_project_calculated_idx" ON "project_momentum" USING btree ("project_id","calculated_at");--> statement-breakpoint
CREATE INDEX "project_momentum_rank_idx" ON "project_momentum" USING btree ("calculated_at","score");--> statement-breakpoint
CREATE UNIQUE INDEX "search_alias_project_normalized_idx" ON "search_aliases" USING btree ("project_id","normalized_alias");--> statement-breakpoint
CREATE INDEX "search_alias_normalized_idx" ON "search_aliases" USING btree ("normalized_alias");
--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN "search_document" tsvector GENERATED ALWAYS AS (
  setweight(to_tsvector('english'::regconfig, coalesce("name", '')), 'A') ||
  setweight(to_tsvector('english'::regconfig, coalesce("short_description", '') || ' ' || coalesce("project_type", '')), 'B') ||
  setweight(to_tsvector('english'::regconfig, coalesce("why_interesting", '') || ' ' || coalesce("editorial_description", '')), 'C')
) STORED;
--> statement-breakpoint
CREATE INDEX "projects_search_document_idx" ON "projects" USING gin ("search_document");
--> statement-breakpoint
UPDATE "facets" SET "description" = CASE "slug"
  WHEN 'typescript' THEN 'Type-safe tools and frameworks for modern JavaScript teams.'
  WHEN 'javascript' THEN 'Projects built for the web platform and JavaScript runtime ecosystem.'
  WHEN 'dart' THEN 'Dart tools for cross-platform application development.'
  WHEN 'go' THEN 'Go projects for compact, operationally direct backend systems.'
  WHEN 'python' THEN 'Python tools spanning backend services, data, and AI applications.'
  WHEN 'infrastructure-as-code' THEN 'Declarative tools for provisioning and governing infrastructure.'
  WHEN 'containers' THEN 'Tools for packaging, scheduling, and operating container workloads.'
  WHEN 'opentelemetry' THEN 'Vendor-neutral instrumentation and telemetry pipelines.'
  WHEN 'dashboards' THEN 'Operational visualization and investigation surfaces.'
  WHEN 'ai-applications' THEN 'Frameworks and SDKs for production AI application work.'
  WHEN 'local-models' THEN 'Runtimes and tools for running models on developer-owned hardware.'
  ELSE "description"
END;
--> statement-breakpoint
WITH assignments("project_slug", "facet_slug") AS (VALUES
  ('react','typescript'), ('react','javascript'), ('svelte','typescript'), ('svelte','javascript'),
  ('fastify','typescript'), ('fastify','javascript'), ('hono','typescript'), ('hono','javascript'),
  ('flutter','dart'), ('expo','typescript'), ('expo','javascript'),
  ('opentofu','infrastructure-as-code'), ('kubernetes','containers'),
  ('opentelemetry','opentelemetry'), ('grafana','dashboards'), ('grafana','opentelemetry'),
  ('langchain','python'), ('langchain','typescript'), ('langchain','ai-applications'),
  ('ollama','local-models'), ('ollama','ai-applications')
)
INSERT INTO "project_facets" ("project_id", "facet_id")
SELECT projects."id", facets."id" FROM assignments
JOIN projects ON projects."slug" = assignments."project_slug"
JOIN facets ON facets."slug" = assignments."facet_slug"
ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "facets" ("kind", "slug", "name", "description") VALUES
  ('language','rust','Rust','Memory-safe systems tools and web runtimes.'),
  ('language','kotlin','Kotlin','Kotlin tools for Android and shared application code.'),
  ('language','swift','Swift','Swift projects for Apple-platform application development.'),
  ('ecosystem','ci-cd','CI/CD','Automation for building, testing, and shipping software.'),
  ('ecosystem','error-tracking','Error Tracking','Tools for finding, grouping, and diagnosing application failures.'),
  ('ecosystem','coding-agents','Coding Agents','AI tools that help developers understand and change code.'),
  ('ecosystem','ai-sdks','AI SDKs','Typed libraries for building model-powered product features.'),
  ('ecosystem','model-infrastructure','Model Infrastructure','Serving and operating language models in production.')
ON CONFLICT ("kind", "slug") DO UPDATE SET "description" = EXCLUDED."description";
--> statement-breakpoint
WITH seed("slug","name","short_description","editorial_description","why_interesting","best_for","not_ideal_for","project_type","category_slug","open_source","license","self_hostable","pricing_label","pricing_summary","recommended","worth_watching","website","docs","repo") AS (VALUES
('nextjs','Next.js','A React framework for server-rendered and full-stack web applications.','Next.js combines React rendering, routing, server functions, and deployment-oriented conventions in one widely adopted framework.','It remains an important reference point for teams evaluating production React architecture and rendering tradeoffs.','["React products that need server rendering and an integrated application framework"]'::jsonb,'["Teams that want framework-neutral deployment behavior"]'::jsonb,'Framework','frontend',true,'MIT',true,'Open Source','The framework is open source; hosting and managed platform features have separate costs.',true,false,'https://nextjs.org','https://nextjs.org/docs','https://github.com/vercel/next.js'),
('vue','Vue','A progressive component framework for building web user interfaces.','Vue provides a carefully layered component model that can scale from enhanced pages to full applications with its official ecosystem.','Its approachable templates and mature tooling make it a credible alternative to React-centered frontend stacks.','["Teams wanting an approachable reactive component system"]'::jsonb,'["Products standardized on React-only libraries"]'::jsonb,'Framework','frontend',true,'MIT',true,'Open Source','Vue is free and open source; deployment costs depend on the selected platform.',true,false,'https://vuejs.org','https://vuejs.org/guide/','https://github.com/vuejs/core'),
('astro','Astro','A content-focused web framework that minimizes client-side JavaScript.','Astro renders content-first sites with server or static output while allowing interactive components from several UI ecosystems.','Its islands architecture gives editorial and documentation teams a direct way to control browser JavaScript cost.','["Content-heavy sites that need selective interactivity"]'::jsonb,'["Highly interactive applications built around one client runtime"]'::jsonb,'Framework','frontend',true,'MIT',true,'Open Source','Astro is free and open source; managed deployment is optional.',true,false,'https://astro.build','https://docs.astro.build','https://github.com/withastro/astro'),
('tailwind-css','Tailwind CSS','A utility-first CSS framework with a build-time design vocabulary.','Tailwind CSS turns constrained utility classes into a composable styling language supported by build tooling and a large ecosystem.','It is useful when teams want fast interface iteration without inventing one-off CSS conventions for every component.','["Product teams building a consistent custom interface"]'::jsonb,'["Teams that prefer semantic component classes in authored CSS"]'::jsonb,'Styling system','frontend',true,'MIT',true,'Open Source','The framework is free and open source; commercial companion products are separate.',false,false,'https://tailwindcss.com','https://tailwindcss.com/docs','https://github.com/tailwindlabs/tailwindcss'),
('better-auth','Better Auth','A TypeScript authentication framework with a plugin-oriented server API.','Better Auth provides sessions, social sign-in, account flows, and database adapters while keeping authentication logic inside the application boundary.','It gives TypeScript teams a self-hosted alternative to fully managed identity products without starting from primitives.','["TypeScript applications that want to own authentication data"]'::jsonb,'["Teams that require a fully managed enterprise identity service"]'::jsonb,'Authentication','backend',true,'MIT',true,'Open Source','The framework is free and self-hostable; email, database, and OAuth infrastructure may cost money.',true,false,'https://www.better-auth.com','https://www.better-auth.com/docs','https://github.com/better-auth/better-auth'),
('deno','Deno','A secure JavaScript and TypeScript runtime with integrated tooling.','Deno combines a modern runtime, TypeScript support, standard web APIs, and first-party developer tooling in one distribution.','Its web-standard approach is worth evaluating for teams that want fewer separate runtime tools and portable server code.','["TypeScript services that value integrated runtime tooling"]'::jsonb,'["Applications dependent on Node-specific native modules"]'::jsonb,'Runtime','backend',true,'MIT',true,'Open Source','The runtime is free and self-hostable; Deno Deploy offers separate hosted plans.',false,false,'https://deno.com','https://docs.deno.com','https://github.com/denoland/deno'),
('bun','Bun','A JavaScript runtime and toolkit focused on speed and integration.','Bun packages a runtime, package manager, test runner, and bundler around a Node-compatible JavaScript environment.','It is a meaningful option for teams testing whether a faster integrated toolchain can simplify local and server workflows.','["JavaScript and TypeScript teams evaluating an integrated toolchain"]'::jsonb,'["Production systems requiring complete Node compatibility guarantees"]'::jsonb,'Runtime','backend',true,'MIT',true,'Open Source','Bun is free and open source; infrastructure costs depend on where it runs.',false,true,'https://bun.com','https://bun.com/docs','https://github.com/oven-sh/bun'),
('django','Django','A batteries-included Python framework for database-backed web applications.','Django combines routing, data access, forms, authentication, and administration conventions in a long-established Python framework.','Its cohesive defaults remain valuable when a team needs to ship a conventional data-backed product with fewer architectural choices.','["Python teams building content and database-backed applications"]'::jsonb,'["Small asynchronous APIs that need only a thin HTTP layer"]'::jsonb,'Framework','backend',true,'BSD-3-Clause',true,'Open Source','Django is free and self-hostable; deployment and managed services have separate costs.',true,false,'https://www.djangoproject.com','https://docs.djangoproject.com','https://github.com/django/django'),
('postgresql','PostgreSQL','An open-source relational database with a broad extension ecosystem.','PostgreSQL combines transactional relational storage, advanced indexing, JSON support, full-text search, and extensibility in one durable database.','It is a strong default when product data needs consistency today and room for richer queries tomorrow.','["Applications that need reliable relational data and expressive queries"]'::jsonb,'["Workloads designed exclusively around globally distributed key-value access"]'::jsonb,'Database','backend',true,'PostgreSQL',true,'Open Source','PostgreSQL is free and self-hostable; managed database services charge for infrastructure.',true,false,'https://www.postgresql.org','https://www.postgresql.org/docs/','https://github.com/postgres/postgres'),
('react-native','React Native','A React renderer for building native iOS and Android applications.','React Native lets teams express mobile interfaces with React while rendering platform-native views and retaining access to native modules.','It offers a pragmatic path for React teams to share skills and selected code across mobile platforms.','["React teams building native mobile products"]'::jsonb,'["Apps whose interface and architecture are entirely platform-specific"]'::jsonb,'Framework','mobile',true,'MIT',true,'Open Source','React Native is free and open source; build, store, and backend services may cost money.',true,false,'https://reactnative.dev','https://reactnative.dev/docs/getting-started','https://github.com/facebook/react-native'),
('kotlin-multiplatform','Kotlin Multiplatform','A Kotlin technology for sharing application logic across platforms.','Kotlin Multiplatform supports shared business logic while allowing teams to retain native platform interfaces and integrations where needed.','It is compelling for teams that want deliberate code sharing without forcing every screen into one cross-platform rendering layer.','["Mobile teams sharing domain and data code across Android and iOS"]'::jsonb,'["Teams seeking one identical UI implementation on every platform"]'::jsonb,'SDK','mobile',true,'Apache-2.0',true,'Open Source','The Kotlin toolchain is free and open source; platform tooling and services vary.',false,false,'https://kotlinlang.org/docs/multiplatform.html','https://kotlinlang.org/docs/multiplatform-get-started.html','https://github.com/JetBrains/kotlin'),
('capacitor','Capacitor','A native runtime for shipping web applications on mobile platforms.','Capacitor packages web applications for iOS and Android and exposes native capabilities through a plugin interface.','It gives web teams a measured route into app stores when reusing an existing browser application matters.','["Web teams adapting an existing application for mobile distribution"]'::jsonb,'["Interfaces requiring deeply native rendering and interaction throughout"]'::jsonb,'Runtime','mobile',true,'MIT',true,'Open Source','The runtime is free and open source; Ionic offers optional commercial tooling and services.',false,false,'https://capacitorjs.com','https://capacitorjs.com/docs','https://github.com/ionic-team/capacitor'),
('tauri','Tauri','A Rust-based toolkit for small cross-platform desktop and mobile applications.','Tauri pairs web frontend technologies with a Rust host and operating-system webviews to produce compact cross-platform applications.','Its security model and smaller distribution footprint make it worth comparing with bundled-browser desktop runtimes.','["Teams building compact cross-platform apps with web UI skills"]'::jsonb,'["Products requiring identical browser engine behavior on every device"]'::jsonb,'Framework','mobile',true,'MIT OR Apache-2.0',true,'Open Source','Tauri is free and self-hostable; signing, distribution, and backend services may cost money.',false,true,'https://tauri.app','https://tauri.app/start/','https://github.com/tauri-apps/tauri'),
('docker','Docker Engine','A container runtime and toolchain for packaging application workloads.','Docker Engine supplies the familiar image, container, networking, and build primitives behind many local and production delivery workflows.','Its image format and developer workflow remain a common interoperability boundary across modern infrastructure.','["Teams standardizing reproducible application environments"]'::jsonb,'["Workloads that do not benefit from process isolation or image distribution"]'::jsonb,'Container runtime','devops',true,'Apache-2.0',true,'Open Source','Docker Engine is open source; Docker Desktop and hosted services have separate terms and plans.',true,false,'https://www.docker.com','https://docs.docker.com/engine/','https://github.com/moby/moby'),
('pulumi','Pulumi','An infrastructure-as-code platform using general-purpose programming languages.','Pulumi models cloud infrastructure through familiar languages and libraries while tracking deployment state through local or managed backends.','It gives software teams typed abstractions and testing patterns when configuration-only infrastructure becomes limiting.','["Teams managing infrastructure with TypeScript, Python, Go, or C#"]'::jsonb,'["Organizations that prefer a vendor-neutral declarative language standard"]'::jsonb,'Infrastructure as code','devops',true,'Apache-2.0',true,'Generous Free Tier','The SDK and local workflows are open source; Pulumi Cloud offers free and paid plans.',true,false,'https://www.pulumi.com','https://www.pulumi.com/docs/','https://github.com/pulumi/pulumi'),
('ansible','Ansible','An agentless automation tool for configuring systems and applications.','Ansible expresses repeatable operations in playbooks and connects to managed machines without installing a persistent agent on each target.','It remains useful for configuration and operational automation that sits outside a container orchestrator or cloud control plane.','["Infrastructure teams automating system configuration and repeatable operations"]'::jsonb,'["Teams seeking a strongly typed cloud resource programming model"]'::jsonb,'Automation','devops',true,'GPL-3.0',true,'Open Source','Ansible community tooling is free and self-hostable; enterprise automation products are separate.',false,false,'https://www.ansible.com','https://docs.ansible.com','https://github.com/ansible/ansible'),
('argo-cd','Argo CD','A declarative GitOps delivery controller for Kubernetes.','Argo CD continuously reconciles Kubernetes application state against version-controlled declarations and exposes delivery health and history.','It makes deployment drift visible and gives platform teams a focused GitOps control plane for Kubernetes workloads.','["Kubernetes teams adopting declarative continuous delivery"]'::jsonb,'["Products that do not operate Kubernetes clusters"]'::jsonb,'CI/CD','devops',true,'Apache-2.0',true,'Open Source','Argo CD is free and self-hostable; cluster infrastructure and commercial support may cost money.',true,false,'https://argo-cd.readthedocs.io','https://argo-cd.readthedocs.io/en/stable/','https://github.com/argoproj/argo-cd'),
('vercel','Vercel','A managed frontend cloud for web application deployment and delivery.','Vercel combines build automation, preview environments, server runtimes, edge delivery, and platform observability around modern web frameworks.','Its integrated workflow is a useful benchmark for teams optimizing for rapid web delivery and low initial operations work.','["Web teams prioritizing previews and managed global delivery"]'::jsonb,'["Teams requiring cloud-neutral infrastructure and fully self-hosted control"]'::jsonb,'Deployment platform','devops',false,NULL,false,'Generous Free Tier','A free personal tier exists; production teams and higher usage move to paid plans.',true,false,'https://vercel.com','https://vercel.com/docs','https://github.com/vercel/vercel'),
('prometheus','Prometheus','A time-series monitoring system with a pull-based metrics model.','Prometheus collects labeled metrics, evaluates alerting rules, and supports a broad ecosystem of exporters and compatible storage systems.','Its data model and query language remain foundational for cloud-native metrics even when long-term storage is delegated elsewhere.','["Teams operating infrastructure and service metrics"]'::jsonb,'["Long-term high-cardinality event analytics without additional systems"]'::jsonb,'Monitoring','observability',true,'Apache-2.0',true,'Open Source','Prometheus is free and self-hostable; storage and managed services may add cost.',true,false,'https://prometheus.io','https://prometheus.io/docs/','https://github.com/prometheus/prometheus'),
('jaeger','Jaeger','A distributed tracing platform built around open telemetry standards.','Jaeger receives, stores, and visualizes distributed traces so teams can follow requests across service boundaries and investigate latency.','It is a focused open-source tracing backend for teams standardizing instrumentation around OpenTelemetry.','["Service teams investigating distributed request paths"]'::jsonb,'["Teams seeking a complete metrics, logs, and incident platform in one product"]'::jsonb,'Tracing','observability',true,'Apache-2.0',true,'Open Source','Jaeger is free and self-hostable; storage and operations infrastructure carry costs.',false,false,'https://www.jaegertracing.io','https://www.jaegertracing.io/docs/','https://github.com/jaegertracing/jaeger'),
('signoz','SigNoz','An open-source observability platform for traces, metrics, and logs.','SigNoz combines OpenTelemetry ingestion with application performance views, logs, dashboards, and alerts in one deployable product.','It gives teams a self-hostable integrated observability option built around portable instrumentation.','["Teams wanting one OpenTelemetry-native observability interface"]'::jsonb,'["Organizations that do not want to operate analytical storage"]'::jsonb,'Observability platform','observability',true,'MIT',true,'Generous Free Tier','The community edition is self-hostable; SigNoz Cloud has free and paid plans.',true,false,'https://signoz.io','https://signoz.io/docs/','https://github.com/SigNoz/signoz'),
('loki','Grafana Loki','A log aggregation system designed around labels and object storage.','Loki indexes compact metadata labels while storing log content in cost-oriented backends and integrating closely with Grafana.','Its architecture is attractive when teams want familiar Prometheus-style labels without building a full-text index for every log line.','["Teams centralizing cloud-native logs with Grafana"]'::jsonb,'["Use cases requiring arbitrary full-text analytics across every field"]'::jsonb,'Logging','observability',true,'AGPL-3.0',true,'Open Source','Loki is self-hostable; Grafana Cloud and storage infrastructure have separate costs.',false,false,'https://grafana.com/oss/loki/','https://grafana.com/docs/loki/latest/','https://github.com/grafana/loki'),
('sentry','Sentry','An application monitoring platform centered on errors and performance.','Sentry groups application exceptions with releases, traces, user impact, and source context to help teams move from alert to diagnosis.','Its developer-focused error workflow makes it a practical first operational signal for product teams shipping frequently.','["Product teams prioritizing actionable application error diagnosis"]'::jsonb,'["Teams seeking only infrastructure metrics or raw log storage"]'::jsonb,'Error tracking','observability',true,'FSL-1.1-Apache-2.0',true,'Generous Free Tier','Sentry can be self-hosted and its cloud service offers free and paid plans under current vendor terms.',true,false,'https://sentry.io','https://docs.sentry.io','https://github.com/getsentry/sentry'),
('ai-sdk','AI SDK','A TypeScript toolkit for building model-powered application features.','AI SDK provides provider-neutral model calls, structured generation, tool use, streaming, and UI integrations for TypeScript applications.','Its typed interface reduces provider-specific application code while preserving access to streaming and agent-oriented primitives.','["TypeScript products integrating several model providers"]'::jsonb,'["Teams that need a complete model hosting platform rather than an application SDK"]'::jsonb,'SDK','ai-tools',true,'Apache-2.0',true,'Open Source','The SDK is free and open source; model provider and hosting usage are billed separately.',true,false,'https://ai-sdk.dev','https://ai-sdk.dev/docs','https://github.com/vercel/ai'),
('llamaindex','LlamaIndex','A framework for connecting application data to language models.','LlamaIndex provides ingestion, retrieval, indexing, agent, and evaluation components across Python and TypeScript ecosystems.','It is worth evaluating when an AI product needs a structured data and retrieval layer beyond direct model calls.','["AI applications centered on retrieval and private data sources"]'::jsonb,'["Simple prompts that need only a model provider SDK"]'::jsonb,'Framework','ai-tools',true,'MIT',true,'Open Source','Core frameworks are open source; managed LlamaCloud services have separate plans.',false,false,'https://www.llamaindex.ai','https://docs.llamaindex.ai','https://github.com/run-llama/llama_index'),
('vllm','vLLM','A high-throughput open-source server for large language models.','vLLM focuses on efficient model serving with continuous batching, optimized memory management, and an OpenAI-compatible HTTP surface.','It is a serious infrastructure option when teams operate open models and need higher serving utilization than a basic local runtime.','["Teams serving open language models on GPU infrastructure"]'::jsonb,'["Developers who only need lightweight local model experiments"]'::jsonb,'Model server','ai-tools',true,'Apache-2.0',true,'Open Source','vLLM is free and self-hostable; GPU infrastructure is the primary operating cost.',true,false,'https://vllm.ai','https://docs.vllm.ai','https://github.com/vllm-project/vllm'),
('continue','Continue','An open-source platform for AI coding assistants and agents.','Continue supplies editor and command-line surfaces for configurable coding assistance connected to different models and development contexts.','Its open configuration and model flexibility make it useful for teams that want to shape an AI coding workflow around their own constraints.','["Developers configuring model-flexible coding assistance"]'::jsonb,'["Teams wanting a completely managed coding environment with no setup"]'::jsonb,'Coding agent','ai-tools',true,'Apache-2.0',true,'Open Source','Core software is open source; model inference and hosted services can have separate costs.',false,true,'https://continue.dev','https://docs.continue.dev','https://github.com/continuedev/continue')
)
INSERT INTO "projects" ("slug","name","short_description","editorial_description","why_interesting","best_for","not_ideal_for","project_type","category_id","status","open_source","license","self_hostable","pricing_label","pricing_summary","recommended","worth_watching","reviewed_at","published_at")
SELECT seed."slug",seed."name",seed."short_description",seed."editorial_description",seed."why_interesting",seed."best_for",seed."not_ideal_for",seed."project_type",categories."id",'published',seed."open_source",seed."license",seed."self_hostable",seed."pricing_label",seed."pricing_summary",seed."recommended",seed."worth_watching",'2026-09-04T00:00:00Z','2026-09-04T00:00:00Z'
FROM seed JOIN categories ON categories."slug"=seed."category_slug" ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
WITH details("slug","website","docs","repo") AS (SELECT * FROM (VALUES
('nextjs','https://nextjs.org','https://nextjs.org/docs','https://github.com/vercel/next.js'),('vue','https://vuejs.org','https://vuejs.org/guide/','https://github.com/vuejs/core'),('astro','https://astro.build','https://docs.astro.build','https://github.com/withastro/astro'),('tailwind-css','https://tailwindcss.com','https://tailwindcss.com/docs','https://github.com/tailwindlabs/tailwindcss'),('better-auth','https://www.better-auth.com','https://www.better-auth.com/docs','https://github.com/better-auth/better-auth'),('deno','https://deno.com','https://docs.deno.com','https://github.com/denoland/deno'),('bun','https://bun.com','https://bun.com/docs','https://github.com/oven-sh/bun'),('django','https://www.djangoproject.com','https://docs.djangoproject.com','https://github.com/django/django'),('postgresql','https://www.postgresql.org','https://www.postgresql.org/docs/','https://github.com/postgres/postgres'),('react-native','https://reactnative.dev','https://reactnative.dev/docs/getting-started','https://github.com/facebook/react-native'),('kotlin-multiplatform','https://kotlinlang.org/docs/multiplatform.html','https://kotlinlang.org/docs/multiplatform-get-started.html','https://github.com/JetBrains/kotlin'),('capacitor','https://capacitorjs.com','https://capacitorjs.com/docs','https://github.com/ionic-team/capacitor'),('tauri','https://tauri.app','https://tauri.app/start/','https://github.com/tauri-apps/tauri'),('docker','https://www.docker.com','https://docs.docker.com/engine/','https://github.com/moby/moby'),('pulumi','https://www.pulumi.com','https://www.pulumi.com/docs/','https://github.com/pulumi/pulumi'),('ansible','https://www.ansible.com','https://docs.ansible.com','https://github.com/ansible/ansible'),('argo-cd','https://argo-cd.readthedocs.io','https://argo-cd.readthedocs.io/en/stable/','https://github.com/argoproj/argo-cd'),('vercel','https://vercel.com','https://vercel.com/docs','https://github.com/vercel/vercel'),('prometheus','https://prometheus.io','https://prometheus.io/docs/','https://github.com/prometheus/prometheus'),('jaeger','https://www.jaegertracing.io','https://www.jaegertracing.io/docs/','https://github.com/jaegertracing/jaeger'),('signoz','https://signoz.io','https://signoz.io/docs/','https://github.com/SigNoz/signoz'),('loki','https://grafana.com/oss/loki/','https://grafana.com/docs/loki/latest/','https://github.com/grafana/loki'),('sentry','https://sentry.io','https://docs.sentry.io','https://github.com/getsentry/sentry'),('ai-sdk','https://ai-sdk.dev','https://ai-sdk.dev/docs','https://github.com/vercel/ai'),('llamaindex','https://www.llamaindex.ai','https://docs.llamaindex.ai','https://github.com/run-llama/llama_index'),('vllm','https://vllm.ai','https://docs.vllm.ai','https://github.com/vllm-project/vllm'),('continue','https://continue.dev','https://docs.continue.dev','https://github.com/continuedev/continue')) v)
, links AS (SELECT "slug",'website' kind,"website" url FROM details UNION ALL SELECT "slug",'documentation',"docs" FROM details UNION ALL SELECT "slug",'repository',"repo" FROM details)
INSERT INTO "project_links" ("project_id","kind","url","last_successful_check_at") SELECT projects."id",links.kind,links.url,'2026-09-04T00:00:00Z' FROM links JOIN projects USING ("slug") ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "project_sources" ("project_id","claim","source_type","url","checked_at","checked_by") SELECT projects."id",'Official documentation, repository, license, and product facts','maintainer',project_links."url",'2026-09-04T00:00:00Z','HowToBuild.dev editorial' FROM projects JOIN project_links ON project_links."project_id"=projects."id" AND project_links."kind"='repository' WHERE projects."published_at"='2026-09-04T00:00:00Z' AND NOT EXISTS (SELECT 1 FROM project_sources ps WHERE ps."project_id"=projects."id");
--> statement-breakpoint
WITH assignments("project_slug","facet_slug") AS (VALUES ('nextjs','typescript'),('vue','typescript'),('astro','typescript'),('tailwind-css','javascript'),('better-auth','typescript'),('deno','typescript'),('bun','typescript'),('django','python'),('postgresql','typescript'),('react-native','typescript'),('kotlin-multiplatform','kotlin'),('capacitor','typescript'),('tauri','rust'),('docker','containers'),('pulumi','infrastructure-as-code'),('ansible','infrastructure-as-code'),('argo-cd','ci-cd'),('vercel','ci-cd'),('prometheus','opentelemetry'),('jaeger','opentelemetry'),('signoz','opentelemetry'),('loki','dashboards'),('sentry','error-tracking'),('ai-sdk','ai-sdks'),('llamaindex','ai-applications'),('vllm','model-infrastructure'),('continue','coding-agents')) INSERT INTO "project_facets" SELECT projects."id",facets."id" FROM assignments JOIN projects ON projects."slug"=assignments."project_slug" JOIN facets ON facets."slug"=assignments."facet_slug" ON CONFLICT DO NOTHING;
--> statement-breakpoint
WITH aliases("project_slug","alias") AS (VALUES ('better-auth','auth'),('better-auth','authentication'),('fastify','typescript backend'),('hono','typescript backend'),('postgresql','postgres'),('vercel','free hosting'),('continue','ai coding'),('continue','coding agent'),('pulumi','iac'),('argo-cd','gitops'),('react-native','react native'),('ai-sdk','vercel ai sdk'),('vllm','model serving')) INSERT INTO "search_aliases" ("project_id","alias","normalized_alias") SELECT projects."id",aliases."alias",lower(aliases."alias") FROM aliases JOIN projects ON projects."slug"=aliases."project_slug" ON CONFLICT DO NOTHING;
--> statement-breakpoint
WITH details("slug","owner","name") AS (VALUES ('nextjs','vercel','next.js'),('vue','vuejs','core'),('astro','withastro','astro'),('tailwind-css','tailwindlabs','tailwindcss'),('better-auth','better-auth','better-auth'),('deno','denoland','deno'),('bun','oven-sh','bun'),('django','django','django'),('postgresql','postgres','postgres'),('react-native','facebook','react-native'),('kotlin-multiplatform','JetBrains','kotlin'),('capacitor','ionic-team','capacitor'),('tauri','tauri-apps','tauri'),('docker','moby','moby'),('pulumi','pulumi','pulumi'),('ansible','ansible','ansible'),('argo-cd','argoproj','argo-cd'),('vercel','vercel','vercel'),('prometheus','prometheus','prometheus'),('jaeger','jaegertracing','jaeger'),('signoz','SigNoz','signoz'),('loki','grafana','loki'),('sentry','getsentry','sentry'),('ai-sdk','vercel','ai'),('llamaindex','run-llama','llama_index'),('vllm','vllm-project','vllm'),('continue','continuedev','continue')), inserted AS (INSERT INTO "repositories" ("github_node_id","owner","name") SELECT 'pending:'||lower("owner")||'/'||lower("name"),"owner","name" FROM details ON CONFLICT ("owner","name") DO UPDATE SET "owner"=EXCLUDED."owner" RETURNING "id","owner","name") INSERT INTO "project_repositories" SELECT projects."id",inserted."id",true FROM details JOIN projects ON projects."slug"=details."slug" JOIN inserted ON lower(inserted."owner")=lower(details."owner") AND lower(inserted."name")=lower(details."name") ON CONFLICT DO NOTHING;
--> statement-breakpoint
WITH aliases("project_slug", "alias") AS (VALUES
  ('react','react.js'), ('svelte','sveltekit'), ('fastify','node api'),
  ('hono','edge api'), ('flutter','cross platform mobile'), ('expo','react native'),
  ('opentofu','terraform alternative'), ('opentofu','iac'), ('kubernetes','k8s'),
  ('opentelemetry','otel'), ('grafana','monitoring dashboards'),
  ('langchain','llm framework'), ('langchain','ai application framework'),
  ('ollama','local llm')
)
INSERT INTO "search_aliases" ("project_id", "alias", "normalized_alias")
SELECT projects."id", aliases."alias", lower(aliases."alias") FROM aliases
JOIN projects ON projects."slug" = aliases."project_slug"
ON CONFLICT DO NOTHING;
--> statement-breakpoint
WITH coordinates("project_slug", "owner", "name") AS (VALUES
  ('react','facebook','react'), ('svelte','sveltejs','svelte'),
  ('fastify','fastify','fastify'), ('hono','honojs','hono'),
  ('flutter','flutter','flutter'), ('expo','expo','expo'),
  ('opentofu','opentofu','opentofu'), ('kubernetes','kubernetes','kubernetes'),
  ('opentelemetry','open-telemetry','opentelemetry-specification'),
  ('grafana','grafana','grafana'), ('langchain','langchain-ai','langchain'),
  ('ollama','ollama','ollama')
), inserted AS (
  INSERT INTO "repositories" ("github_node_id", "owner", "name")
  SELECT 'pending:' || lower("owner") || '/' || lower("name"), "owner", "name" FROM coordinates
  ON CONFLICT ("owner", "name") DO UPDATE SET "owner" = EXCLUDED."owner"
  RETURNING "id", "owner", "name"
)
INSERT INTO "project_repositories" ("project_id", "repository_id", "is_default")
SELECT projects."id", inserted."id", true FROM coordinates
JOIN projects ON projects."slug" = coordinates."project_slug"
JOIN inserted ON lower(inserted."owner") = lower(coordinates."owner") AND lower(inserted."name") = lower(coordinates."name")
ON CONFLICT DO NOTHING;
