/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as CategoryEcosystemRouteImport } from './routes/$category.$ecosystem'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminMetricsRouteImport } from './routes/admin/metrics'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PreviewProjectRouteImport } from './routes/preview/$project'
import { Route as ProjectsProjectRouteImport } from './routes/projects/$project'
import { Route as AdminProjectsProjectRouteImport } from './routes/admin/projects/$project'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiJobsGithubRouteImport } from './routes/api/jobs/github'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryEcosystemRoute = CategoryEcosystemRouteImport.update({
  id: '/$ecosystem',
  path: '/$ecosystem',
  getParentRoute: () => CategoryRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/admin/metrics',
  path: '/admin/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProjectRoute = PreviewProjectRouteImport.update({
  id: '/preview/$project',
  path: '/preview/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsProjectRoute = AdminProjectsProjectRouteImport.update({
  id: '/admin/projects/$project',
  path: '/admin/projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsGithubRoute = ApiJobsGithubRouteImport.update({
  id: '/api/jobs/github',
  path: '/api/jobs/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trending': typeof TrendingRoute
  '/$category/$ecosystem': typeof CategoryEcosystemRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/api/health': typeof ApiHealthRoute
  '/preview/$project': typeof PreviewProjectRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/projects/$project': typeof AdminProjectsProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/github': typeof ApiJobsGithubRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trending': typeof TrendingRoute
  '/$category/$ecosystem': typeof CategoryEcosystemRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/api/health': typeof ApiHealthRoute
  '/preview/$project': typeof PreviewProjectRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/admin': typeof AdminIndexRoute
  '/admin/projects/$project': typeof AdminProjectsProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/github': typeof ApiJobsGithubRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trending': typeof TrendingRoute
  '/$category/$ecosystem': typeof CategoryEcosystemRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/api/health': typeof ApiHealthRoute
  '/preview/$project': typeof PreviewProjectRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/projects/$project': typeof AdminProjectsProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/github': typeof ApiJobsGithubRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/robots.txt'
    | '/search'
    | '/sign-in'
    | '/sitemap.xml'
    | '/trending'
    | '/$category/$ecosystem'
    | '/admin/metrics'
    | '/api/health'
    | '/preview/$project'
    | '/projects/$project'
    | '/admin/'
    | '/admin/projects/$project'
    | '/api/auth/$'
    | '/api/jobs/github'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$category'
    | '/robots.txt'
    | '/search'
    | '/sign-in'
    | '/sitemap.xml'
    | '/trending'
    | '/$category/$ecosystem'
    | '/admin/metrics'
    | '/api/health'
    | '/preview/$project'
    | '/projects/$project'
    | '/admin'
    | '/admin/projects/$project'
    | '/api/auth/$'
    | '/api/jobs/github'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/$category'
    | '/robots.txt'
    | '/search'
    | '/sign-in'
    | '/sitemap.xml'
    | '/trending'
    | '/$category/$ecosystem'
    | '/admin/metrics'
    | '/api/health'
    | '/preview/$project'
    | '/projects/$project'
    | '/admin/'
    | '/admin/projects/$project'
    | '/api/auth/$'
    | '/api/jobs/github'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrendingRoute: typeof TrendingRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PreviewProjectRoute: typeof PreviewProjectRoute
  ProjectsProjectRoute: typeof ProjectsProjectRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjectsProjectRoute: typeof AdminProjectsProjectRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJobsGithubRoute: typeof ApiJobsGithubRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$ecosystem': {
      id: '/$category/$ecosystem'
      path: '/$ecosystem'
      fullPath: '/$category/$ecosystem'
      preLoaderRoute: typeof CategoryEcosystemRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/admin/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$project': {
      id: '/preview/$project'
      path: '/preview/$project'
      fullPath: '/preview/$project'
      preLoaderRoute: typeof PreviewProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$project': {
      id: '/admin/projects/$project'
      path: '/admin/projects/$project'
      fullPath: '/admin/projects/$project'
      preLoaderRoute: typeof AdminProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/github': {
      id: '/api/jobs/github'
      path: '/api/jobs/github'
      fullPath: '/api/jobs/github'
      preLoaderRoute: typeof ApiJobsGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CategoryRouteChildren {
  CategoryEcosystemRoute: typeof CategoryEcosystemRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryEcosystemRoute: CategoryEcosystemRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrendingRoute: TrendingRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  ApiHealthRoute: ApiHealthRoute,
  PreviewProjectRoute: PreviewProjectRoute,
  ProjectsProjectRoute: ProjectsProjectRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjectsProjectRoute: AdminProjectsProjectRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJobsGithubRoute: ApiJobsGithubRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
