/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CategoryEcosystemRouteImport } from './routes/$category.$ecosystem'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountSubmissionsRouteImport } from './routes/account/submissions'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLinksRouteImport } from './routes/admin/links'
import { Route as AdminMetricsRouteImport } from './routes/admin/metrics'
import { Route as AdminOperationsRouteImport } from './routes/admin/operations'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTelemetryRouteImport } from './routes/api/telemetry'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesGuideRouteImport } from './routes/guides/$guide'
import { Route as PreviewProjectRouteImport } from './routes/preview/$project'
import { Route as ProjectsProjectRouteImport } from './routes/projects/$project'
import { Route as StacksIndexRouteImport } from './routes/stacks/index'
import { Route as StacksStackRouteImport } from './routes/stacks/$stack'
import { Route as SubmitIndexRouteImport } from './routes/submit/index'
import { Route as SubmitGuidelinesRouteImport } from './routes/submit/guidelines'
import { Route as AdminProjectsProjectRouteImport } from './routes/admin/projects/$project'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiJobsGithubRouteImport } from './routes/api/jobs/github'
import { Route as ApiJobsLinksRouteImport } from './routes/api/jobs/links'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ProjectsProjectSuggestRouteImport } from './routes/projects/$project_.suggest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryEcosystemRoute = CategoryEcosystemRouteImport.update({
  id: '/$ecosystem',
  path: '/$ecosystem',
  getParentRoute: () => CategoryRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSubmissionsRoute = AccountSubmissionsRouteImport.update({
  id: '/account/submissions',
  path: '/account/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/admin/links',
  path: '/admin/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/admin/metrics',
  path: '/admin/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryRoute = ApiTelemetryRouteImport.update({
  id: '/api/telemetry',
  path: '/api/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideRoute = GuidesGuideRouteImport.update({
  id: '/guides/$guide',
  path: '/guides/$guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProjectRoute = PreviewProjectRouteImport.update({
  id: '/preview/$project',
  path: '/preview/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIndexRoute = StacksIndexRouteImport.update({
  id: '/stacks/',
  path: '/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksStackRoute = StacksStackRouteImport.update({
  id: '/stacks/$stack',
  path: '/stacks/$stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitIndexRoute = SubmitIndexRouteImport.update({
  id: '/submit/',
  path: '/submit/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitGuidelinesRoute = SubmitGuidelinesRouteImport.update({
  id: '/submit/guidelines',
  path: '/submit/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsProjectRoute = AdminProjectsProjectRouteImport.update({
  id: '/admin/projects/$project',
  path: '/admin/projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsGithubRoute = ApiJobsGithubRouteImport.update({
  id: '/api/jobs/github',
  path: '/api/jobs/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsLinksRoute = ApiJobsLinksRouteImport.update({
  id: '/api/jobs/links',
  path: '/api/jobs/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSuggestRoute = ProjectsProjectSuggestRouteImport.update({
  id: '/projects/$project_/suggest',
  path: '/projects/$project/suggest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/corrections': typeof CorrectionsRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/verify': typeof VerifyRoute
  '/$category/$ecosystem': typeof CategoryEcosystemRoute
  '/account/submissions': typeof AccountSubmissionsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/guides/$guide': typeof GuidesGuideRoute
  '/preview/$project': typeof PreviewProjectRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/stacks/$stack': typeof StacksStackRoute
  '/submit/guidelines': typeof SubmitGuidelinesRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/stacks/': typeof StacksIndexRoute
  '/submit/': typeof SubmitIndexRoute
  '/admin/projects/$project': typeof AdminProjectsProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/github': typeof ApiJobsGithubRoute
  '/api/jobs/links': typeof ApiJobsLinksRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/projects/$project/suggest': typeof ProjectsProjectSuggestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/corrections': typeof CorrectionsRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/verify': typeof VerifyRoute
  '/$category/$ecosystem': typeof CategoryEcosystemRoute
  '/account/submissions': typeof AccountSubmissionsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/guides/$guide': typeof GuidesGuideRoute
  '/preview/$project': typeof PreviewProjectRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/stacks/$stack': typeof StacksStackRoute
  '/submit/guidelines': typeof SubmitGuidelinesRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/stacks': typeof StacksIndexRoute
  '/submit': typeof SubmitIndexRoute
  '/admin/projects/$project': typeof AdminProjectsProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/github': typeof ApiJobsGithubRoute
  '/api/jobs/links': typeof ApiJobsLinksRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/projects/$project/suggest': typeof ProjectsProjectSuggestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/corrections': typeof CorrectionsRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/verify': typeof VerifyRoute
  '/$category/$ecosystem': typeof CategoryEcosystemRoute
  '/account/submissions': typeof AccountSubmissionsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/guides/$guide': typeof GuidesGuideRoute
  '/preview/$project': typeof PreviewProjectRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/stacks/$stack': typeof StacksStackRoute
  '/submit/guidelines': typeof SubmitGuidelinesRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/stacks/': typeof StacksIndexRoute
  '/submit/': typeof SubmitIndexRoute
  '/admin/projects/$project': typeof AdminProjectsProjectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/github': typeof ApiJobsGithubRoute
  '/api/jobs/links': typeof ApiJobsLinksRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/projects/$project_/suggest': typeof ProjectsProjectSuggestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/about'
    | '/advertise'
    | '/corrections'
    | '/methodology'
    | '/privacy'
    | '/report'
    | '/robots.txt'
    | '/search'
    | '/sign-in'
    | '/sitemap.xml'
    | '/terms'
    | '/trending'
    | '/verify'
    | '/$category/$ecosystem'
    | '/account/submissions'
    | '/admin/links'
    | '/admin/metrics'
    | '/admin/operations'
    | '/admin/submissions'
    | '/api/health'
    | '/api/telemetry'
    | '/guides/$guide'
    | '/preview/$project'
    | '/projects/$project'
    | '/stacks/$stack'
    | '/submit/guidelines'
    | '/account/'
    | '/admin/'
    | '/guides/'
    | '/stacks/'
    | '/submit/'
    | '/admin/projects/$project'
    | '/api/auth/$'
    | '/api/jobs/github'
    | '/api/jobs/links'
    | '/api/rpc/$'
    | '/projects/$project/suggest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$category'
    | '/about'
    | '/advertise'
    | '/corrections'
    | '/methodology'
    | '/privacy'
    | '/report'
    | '/robots.txt'
    | '/search'
    | '/sign-in'
    | '/sitemap.xml'
    | '/terms'
    | '/trending'
    | '/verify'
    | '/$category/$ecosystem'
    | '/account/submissions'
    | '/admin/links'
    | '/admin/metrics'
    | '/admin/operations'
    | '/admin/submissions'
    | '/api/health'
    | '/api/telemetry'
    | '/guides/$guide'
    | '/preview/$project'
    | '/projects/$project'
    | '/stacks/$stack'
    | '/submit/guidelines'
    | '/account'
    | '/admin'
    | '/guides'
    | '/stacks'
    | '/submit'
    | '/admin/projects/$project'
    | '/api/auth/$'
    | '/api/jobs/github'
    | '/api/jobs/links'
    | '/api/rpc/$'
    | '/projects/$project/suggest'
  id:
    | '__root__'
    | '/'
    | '/$category'
    | '/about'
    | '/advertise'
    | '/corrections'
    | '/methodology'
    | '/privacy'
    | '/report'
    | '/robots.txt'
    | '/search'
    | '/sign-in'
    | '/sitemap.xml'
    | '/terms'
    | '/trending'
    | '/verify'
    | '/$category/$ecosystem'
    | '/account/submissions'
    | '/admin/links'
    | '/admin/metrics'
    | '/admin/operations'
    | '/admin/submissions'
    | '/api/health'
    | '/api/telemetry'
    | '/guides/$guide'
    | '/preview/$project'
    | '/projects/$project'
    | '/stacks/$stack'
    | '/submit/guidelines'
    | '/account/'
    | '/admin/'
    | '/guides/'
    | '/stacks/'
    | '/submit/'
    | '/admin/projects/$project'
    | '/api/auth/$'
    | '/api/jobs/github'
    | '/api/jobs/links'
    | '/api/rpc/$'
    | '/projects/$project_/suggest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  CorrectionsRoute: typeof CorrectionsRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrendingRoute: typeof TrendingRoute
  VerifyRoute: typeof VerifyRoute
  AccountSubmissionsRoute: typeof AccountSubmissionsRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTelemetryRoute: typeof ApiTelemetryRoute
  GuidesGuideRoute: typeof GuidesGuideRoute
  PreviewProjectRoute: typeof PreviewProjectRoute
  ProjectsProjectRoute: typeof ProjectsProjectRoute
  StacksStackRoute: typeof StacksStackRoute
  SubmitGuidelinesRoute: typeof SubmitGuidelinesRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  StacksIndexRoute: typeof StacksIndexRoute
  SubmitIndexRoute: typeof SubmitIndexRoute
  AdminProjectsProjectRoute: typeof AdminProjectsProjectRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJobsGithubRoute: typeof ApiJobsGithubRoute
  ApiJobsLinksRoute: typeof ApiJobsLinksRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ProjectsProjectSuggestRoute: typeof ProjectsProjectSuggestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$ecosystem': {
      id: '/$category/$ecosystem'
      path: '/$ecosystem'
      fullPath: '/$category/$ecosystem'
      preLoaderRoute: typeof CategoryEcosystemRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/submissions': {
      id: '/account/submissions'
      path: '/account/submissions'
      fullPath: '/account/submissions'
      preLoaderRoute: typeof AccountSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/admin/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/admin/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry': {
      id: '/api/telemetry'
      path: '/api/telemetry'
      fullPath: '/api/telemetry'
      preLoaderRoute: typeof ApiTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guide': {
      id: '/guides/$guide'
      path: '/guides/$guide'
      fullPath: '/guides/$guide'
      preLoaderRoute: typeof GuidesGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$project': {
      id: '/preview/$project'
      path: '/preview/$project'
      fullPath: '/preview/$project'
      preLoaderRoute: typeof PreviewProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/': {
      id: '/stacks/'
      path: '/stacks'
      fullPath: '/stacks/'
      preLoaderRoute: typeof StacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$stack': {
      id: '/stacks/$stack'
      path: '/stacks/$stack'
      fullPath: '/stacks/$stack'
      preLoaderRoute: typeof StacksStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/': {
      id: '/submit/'
      path: '/submit'
      fullPath: '/submit/'
      preLoaderRoute: typeof SubmitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/guidelines': {
      id: '/submit/guidelines'
      path: '/submit/guidelines'
      fullPath: '/submit/guidelines'
      preLoaderRoute: typeof SubmitGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$project': {
      id: '/admin/projects/$project'
      path: '/admin/projects/$project'
      fullPath: '/admin/projects/$project'
      preLoaderRoute: typeof AdminProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/github': {
      id: '/api/jobs/github'
      path: '/api/jobs/github'
      fullPath: '/api/jobs/github'
      preLoaderRoute: typeof ApiJobsGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/links': {
      id: '/api/jobs/links'
      path: '/api/jobs/links'
      fullPath: '/api/jobs/links'
      preLoaderRoute: typeof ApiJobsLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project_/suggest': {
      id: '/projects/$project_/suggest'
      path: '/projects/$project/suggest'
      fullPath: '/projects/$project/suggest'
      preLoaderRoute: typeof ProjectsProjectSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CategoryRouteChildren {
  CategoryEcosystemRoute: typeof CategoryEcosystemRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryEcosystemRoute: CategoryEcosystemRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  CorrectionsRoute: CorrectionsRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrendingRoute: TrendingRoute,
  VerifyRoute: VerifyRoute,
  AccountSubmissionsRoute: AccountSubmissionsRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTelemetryRoute: ApiTelemetryRoute,
  GuidesGuideRoute: GuidesGuideRoute,
  PreviewProjectRoute: PreviewProjectRoute,
  ProjectsProjectRoute: ProjectsProjectRoute,
  StacksStackRoute: StacksStackRoute,
  SubmitGuidelinesRoute: SubmitGuidelinesRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  StacksIndexRoute: StacksIndexRoute,
  SubmitIndexRoute: SubmitIndexRoute,
  AdminProjectsProjectRoute: AdminProjectsProjectRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJobsGithubRoute: ApiJobsGithubRoute,
  ApiJobsLinksRoute: ApiJobsLinksRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ProjectsProjectSuggestRoute: ProjectsProjectSuggestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
